spring:
  application:
    name: gamabetting-admin-api
  dataSource:
    url: "jdbc:mysql://localhost:3306/gamabeting-admin?useTimezone=true&serverTimezone=UTC"
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate.ddl-auto: update
    generate-ddl: true
server:
  port: 8081
  servlet:
    context-path: /admin
security:
  sessions: NEVER
  