spring:
  application:
    name: gamabetting-admin-api
  dataSource:
    url: "jdbc:mysql://localhost:3306/betwin_admin?useTimezone=true&serverTimezone=UTC"
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate.ddl-auto: update
    generate-ddl: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
server:
  port: 8080
  servlet:
    context-path: /betwin-admin
#security:
#  sessions: NEVER
  

# app params
betwin:
  security:
    jwtSecret: meuPauDeTanga
    jwtExpiration: 86400